from django.shortcuts import render


# Create your views here.
def all_chai(request):
    all_chai = [
        {'name': 'Kadak Chai', 'price': '10$', 'description': 'Kadak Chai is a strong tea with a bold taste. It is made by brewing black tea leaves with a combination of spices and milk. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Kadak Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://www.honeywhatscooking.com/wp-content/uploads/2019/04/Kadak-Masala-Chai-3.jpg' }, 
        {'name': 'Adrak Chai', 'price': '15$', 'description': 'Adrak Chai is a type of tea that is made by brewing black tea leaves with ginger and other spices. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Adrak Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://static.toiimg.com/thumb/87098868.cms?imgsize=108058&width=800&height=800' },
        {'name': 'Masala Chai', 'price': '20$', 'description': 'Masala Chai is a type of tea that is made by brewing black tea leaves with a combination of spices and milk. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Masala Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://t4.ftcdn.net/jpg/01/66/87/43/360_F_166874362_kZTGg8x1JgRsSCJgO0GWhrkgSWa4ZqRA.jpg' },
        {'name': 'Kesar Chai', 'price': '25$', 'description': 'Kesar Chai is a type of tea that is made by brewing black tea leaves with saffron and other spices. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Kesar Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://5.imimg.com/data5/SELLER/Default/2022/10/WX/IZ/CE/136900100/kesar-tea-500x500.jpg' },
        {'name': 'Elaichi Chai', 'price': '30$', 'description': 'Elaichi Chai is a type of tea that is made by brewing black tea leaves with cardamom and other spices. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Elaichi Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7p7M9geUva4XdEbBXzXvZ3tm7lzrf9-CByth-roKE0GvFegeMwgcHWy7zd3J1pCSibSg&usqp=CAU' },
        {'name': 'Gulab Chai', 'price': '35$', 'description': 'Gulab Chai is a type of tea that is made by brewing black tea leaves with rose petals and other spices. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Gulab Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5vmRpLhre1AuaOOcnOfKzTI6lzcRdqexbqjbU4TRSFogUMu2vr_-0qnxTYozwWkXMjeM&usqp=CAU' },
        {'name': 'Haldi Chai', 'price': '40$', 'description': 'Haldi Chai is a type of tea that is made by brewing black tea leaves with turmeric and other spices. The tea is boiled until it reaches a rich, dark color and is then sweetened with sugar. Haldi Chai is a popular drink in India and is often enjoyed with snacks or breakfast. It is known for its invigorating flavor and is said to provide a boost of energy.', 'image': 'https://www.shutterstock.com/image-photo/closeup-glass-cup-hot-turmeric-260nw-1898189200.jpg' },
        ]
    return render(request, 'chai/all_chai.html', {'all_chai': all_chai})
